### ISSUE TITLE
Not able to build newt example project on OS X

### ISSUE THREAD

**Issue by NilsMinor** [apache/mynewt-newt#398]
Hey newt-team,

I am trying to run the example project https://mynewt.apache.org/v1_5_0/tutorials/blinky/arduino_zero.html but I have some problems building it.

I followed the instructions from the arduino_zero tutorial.
After creating the target I run newt upgrade I get the following versions.

  ```
    upgrade apache-mynewt-core (1.7.0 --> 1.8.0)
    upgrade apache-mynewt-mcumgr (0.0.0 --> 0.1.0)
    upgrade apache-mynewt-nimble (1.2.0 --> 1.3.0)
    upgrade mcuboot (0.0.0 --> 1.5.0)
    install mynewt_arduino_zero (1.8.0)
```

my project.yml looks like :
```
project.repositories:
    - apache-mynewt-core
    - mynewt_arduino_zero

# Use github's distribution mechanism for core ASF libraries.
# This provides mirroring automatically for us.
#
repository.apache-mynewt-core:
    type: github
    vers: 1-latest
    user: apache
    repo: mynewt-core


repository.mynewt_arduino_zero:
    type: github
    vers: 1-latest
    user: runtimeco
    repo: mynewt_arduino_zero
```
But I am always failing to build the target. The output looks like:
```
Error: repos/apache-mynewt-core/kernel/os/src/os_mempool.c: In function 'os_memblock_from':
repos/apache-mynewt-core/kernel/os/src/os_mempool.c:308:5: error: implicit declaration of function 'static_assert' [-Werror=implicit-function-declaration]
     static_assert(sizeof block_addr == sizeof baddr32,
     ^
cc1: all warnings being treated as errors
```

I am using OS X (10.15.4 Catalina) with the following gcc (gcc --version)

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

Newt version:
```
Apache Newt
   Version: 1.7.0
  Git Hash: 80bcba7
Build Date: 2019-08-06_13:20
```

I tested different newt versions (latest 1.7, 1.8 ..) and I changed the git versions in the project.yml. But I was not able to build the example. What am I doing wrong? Any help would be appreciated :)

BTW, newt looks really like an awesome project!

Thanks,
Nils

UPDATE: ----------------------------------------------------------------------------------------

I updated gcc to 9.3

```
gcc (Homebrew GCC 9.3.0_1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
And also updated newt :

`Apache Newt 1.9.0-dev / b86d086-dirty / 2020-05-04_22:24`

But I still get the same error message :/
