### ISSUE TITLE
mfg command error

### ISSUE THREAD

**Issue by vikrant-proxy** [apache/mynewt-newt#439]
I'm trying to use the mfg command with the following `newt`, and it's running into errors -
```
$ newt version
Apache Newt 1.10.0-dev / fd9df1e-dirty / 2021-05-17_16:21
```

I pulled a simple test app with the following details -

```
targets/nrf52_boot
  app=@mcuboot/boot/mynewt
  bsp=@apache-mynewt-core/hw/bsp/nordic_pca10040
  build_profile=optimized
targets/nrf52_blinky
  app=apps/blinky
  bsp=@apache-mynewt-core/hw/bsp/nordic_pca10040
  build_profile=debug
```

```
First complete build step for both targets
```

```
$ newt mfg create blinky 1
Error: failed to read manifest file: open <path-to-repo>/bin/targets/nrf52_boot/app/boot/mynewt/manifest.json: no such file or directory
```

My `mfg.yml` looks like this -

```
   mfg.targets:
       -
           name: 'targets/nrf52_boot'
           area: FLASH_AREA_BOOTLOADER
           offset: 0

       -
           name: 'targets/nrf52_blinky'
           area: FLASH_AREA_IMAGE_0
           offset: 0

   mfg.meta:
       area: FLASH_AREA_IMAGE_SCRATCH
       offset: 0
```

I believe this is because the bootloader binaries have now moved into `@mcuboot` folder, and `newt` cannot find them anymore.
