### ISSUE TITLE
[restrictions] Not able to use a string comparison as a restriction

### ISSUE THREAD

**Issue by vrahane** [apache/mynewt-newt#443]
Currently this does not work, `spi0` needs to be made a `choice` for it to work or a workaround is to use it as a value and and use the `#` operator to convert it to a string.

```
syscfg.defs:
    CHIP_ONB:
        description: 'On board chip'
        value: 1
        restrictions:
            - 'CHIP_ONB_SPI_BUS == "spi0"'

    CHIP_ONB_SPI_BUS:
        value: 'spi0'
```
