### ISSUE TITLE
Issue with newt mfg create

### ISSUE THREAD

**Issue by estutzenberger** [apache/mynewt-newt#482]
I am having a similar issue to #439, but slightly different behavior. When I try to run the `mfg create` command, I get the following error:
```$ newt mfg create ble2 1.0.0
Error: failed to read manifest file: open <repo-path>/bin/targets/ble2/app/@mcuboot/apps/blehci/manifest.json: no such file or directory
```

`newt` seems to be ignoring the location of the target nrf52_boot and it expects it to exist somewhere else. The manifest that should be found is at `<repopath>bin/targets/nrf52_boot/app/@mcuboot/boot/mynewt/manifest.json`.

Defined targets:
```$ newt target show
targets/ble2
    app=@apache-mynewt-nimble/apps/blehci
    bsp=@apache-mynewt-core/hw/bsp/ublox_bmd_345
    build_profile=optimized
targets/nrf52_boot
    app=@mcuboot/boot/mynewt
    bsp=@apache-mynewt-core/hw/bsp/ublox_bmd_345
    build_profile=optimized
```

mfg.yml file in `mfgs/ble2/`:
```
mfg.bsp: "@apache-mynewt-core/hw/bsp/ublox_bmd_345"
mfg.targets:
    - 
      name: "targets/nrf52_boot"
      area: FLASH_AREA_BOOTLOADER
      offset: 0x0
    - 
      name: "targets/ble2"
      area: FLASH_AREA_IMAGE_0
      offset: 0x0
mfg.meta:
    area: FLASH_AREA_BOOTLOADER
```

Please let me know if something is wrong with my setup.
